#pragma once
//#include<WinUser.h>
#include<Windows.h>
#include<unordered_map>
#undef DELETE

enum class MSKEY;

//キー入力状態
//仮想キーコード,
//入力状態
using KeyList = std::unordered_map<MSKEY, bool>;
extern const KeyList MSKeyList;

enum class MSKEY {
	BACKSPACE = VK_BACK,
	TAB = VK_TAB,
	CLEAR = VK_CLEAR,
	ENTER = VK_RETURN,
	RETURN = VK_RETURN,
	SHIFT = VK_SHIFT,
	CONTROL = VK_CONTROL,
	MENU = VK_MENU,
	PAUSE = VK_PAUSE,
	CAPITAL = VK_CAPITAL,
	ESCAPE = VK_ESCAPE,
	NONCONVERT = VK_NONCONVERT,
	SPACE = VK_SPACE,
	PAGEUP = VK_PRIOR,
	PAGEDOWN = VK_NEXT,
	END = VK_END,
	HOME = VK_HOME,
	LEFT = VK_LEFT,
	UP = VK_UP,
	RIGHT = VK_RIGHT,
	DOWN = VK_DOWN,
	PRINTSCREEN = VK_SNAPSHOT,
	INSERT = VK_INSERT,
	DELETE = VK_DELETE,
	WINDOWSL = VK_LWIN,
	WINDOWSR = VK_RWIN,
	APPLICATION_MENU = VK_APPS,
	NUMPAD0 = VK_NUMPAD0,
	NUMPAD1 = VK_NUMPAD1,
	NUMPAD2 = VK_NUMPAD2,
	NUMPAD3 = VK_NUMPAD3,
	NUMPAD4 = VK_NUMPAD4,
	NUMPAD5 = VK_NUMPAD5,
	NUMPAD6 = VK_NUMPAD6,
	NUMPAD7 = VK_NUMPAD7,
	NUMPAD8 = VK_NUMPAD8,
	NUMPAD9 = VK_NUMPAD9,
	MUTIPLY = VK_MULTIPLY,
	ADD = VK_ADD,
	SUBTRACT = VK_SUBTRACT,
	DECIMAL = VK_DECIMAL,
	DIVIDE = VK_DIVIDE,
	F1 = VK_F1,
	F2 = VK_F2,
	F3 = VK_F3,
	F4 = VK_F4,
	F5 = VK_F5,
	F6 = VK_F6,
	F7 = VK_F7,
	F8 = VK_F8,
	F9 = VK_F9,
	F10 = VK_F10,
	F11 = VK_F11,
	F12 = VK_F12,
	NUMLOCK = VK_NUMLOCK,
	SCROLL = VK_SCROLL,
	COLON = ':',
	SEMICOLON = ';',
	COMMA=',',
	HYPHEN='-',
	PERIOD='.',
	SLASH = '/',
	BACKSLASH = '\\',
	YENMARK='\\',
	BRACKETL = '[',
	BRACKETR=']',
	CAPSLOCK=0xF0,
	CH_0 = '0',
	CH_1 = '1',
	CH_2 = '2',
	CH_3 = '3',
	CH_4 = '4',
	CH_5 = '5',
	CH_6 = '6',
	CH_7 = '7',
	CH_8 = '8',
	CH_9 = '9',
	CH_A = 'A',
	CH_B = 'B',
	CH_C = 'C',
	CH_D = 'D',
	CH_E = 'E',
	CH_F = 'F',
	CH_G = 'G',
	CH_H = 'H',
	CH_I = 'I',
	CH_J = 'J',
	CH_K = 'K',
	CH_L = 'L',
	CH_M = 'M',
	CH_N = 'N',
	CH_O = 'O',
	CH_P = 'P',
	CH_Q = 'Q',
	CH_R = 'R',
	CH_S = 'S',
	CH_T = 'T',
	CH_U = 'U',
	CH_V = 'V',
	CH_W = 'W',
	CH_X = 'X',
	CH_Y = 'Y',
	CH_Z = 'Z',
};
#define DELETE                           (0x00010000L)
